import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-dark-accent-default">franko peder</h1>
        <h1 className="text-dark-accent-strong">franko peder</h1>
        <h1 className="text-dark-accent-medium">franko peder</h1>
        <h1 className="text-dark-accent-weak">franko peder</h1>
        <h1 className="text-dark-neutral-default">franko peder</h1>
        <h1 className="text-dark-neutral-strong">franko peder</h1>
        <h1 className="text-dark-neutral-medium">franko peder</h1>
        <h1 className="text-dark-neutral-weak">franko peder</h1>
        <h1 className="text-dark-success-default">franko peder</h1>
        <h1 className="text-dark-success-weak">franko peder</h1>
        <h1 className="text-dark-danger-default">franko peder</h1>
        <h1 className="text-dark-warning-default">franko peder</h1>
      </div>
    </div>
  );
}
