import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import Article from "../components/Article";
import { Button } from "../components/Button";
import Icon from "../components/Icon";
import Ivanbrcic from "../components/Ivanbrcic";
import Status from "../components/Status";
import Subject from "../components/Subject";
import Table from "../components/Table";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>UniVibe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Sidebar */}
      <div className="flex h-max bg-black">
        <div className="w-[20%] h-screen  ">
          <h1>Homepage</h1>
        </div>

        {/* Main Page */}
        <div className="w-full bg-black p-2">
          <div className="h-[30%] w-[100%] mb-2 bg-[#101010] rounded-xl relative">
            <h1 className="display3 text-white absolute bottom-10 left-10">
              Digitalna Logika
            </h1>
          </div>
          <div className="h-[30%] w-[100%] mb-2 bg-[#181818] rounded-xl "></div>
          <div className="h-[37%] w-[100%] bg-[#101010] rounded-xl "></div>
        </div>
      </div>
      <Ivanbrcic />
    </div>
  );
}
